### ISSUE TITLE
La consulta de Estatus CFDI no deberia ser parte de los servicios de Cancelación. Es necesario separar este servicio de SWCancelationService. 

### ISSUE THREAD

**Issue by hermesw** [lunasoft/sw-sdk-java#34]
![image](https://user-images.githubusercontent.com/6212454/44996927-59a53f80-af70-11e8-8f02-37c89db8b7d5.png)

**Comment by JuanGamezSW** [comment]
Fixed [https://github.com/lunasoft/sw-sdk-java/pull/33/commits/7f78bcb28430eea15e659c21111de58757df0923](https://github.com/lunasoft/sw-sdk-java/pull/33/commits/7f78bcb28430eea15e659c21111de58757df0923)
