### ISSUE TITLE
La consulta de documentos relacionados no es parte del servicio de cancelación. Debe separarse el servicio. Tomar como referencia la librería de .net para ser congruentes entre librerías.

### ISSUE THREAD

**Issue by hermesw** [lunasoft/sw-sdk-java#35]
![image](https://user-images.githubusercontent.com/6212454/44996999-cddfe300-af70-11e8-9b6f-93815e6efb71.png)

**Comment by JuanGamezSW** [comment]
Fixed [https://github.com/lunasoft/sw-sdk-java/pull/33/commits/7f78bcb28430eea15e659c21111de58757df0923](https://github.com/lunasoft/sw-sdk-java/pull/33/commits/7f78bcb28430eea15e659c21111de58757df0923)
