### ISSUE TITLE
La consulta de solicitudes pendientes de Aceptación o Rechazo no es parte del servicio de cancelación. Debe separarse el servicio. Tomar como referencia la librería de .net para ser congruentes entre librerías.

### ISSUE THREAD

**Issue by hermesw** [lunasoft/sw-sdk-java#36]
![image](https://user-images.githubusercontent.com/6212454/44997031-08e21680-af71-11e8-82ff-1bb8ce1b3b1d.png)

**Comment by JuanGamezSW** [comment]
Fixed [https://github.com/lunasoft/sw-sdk-java/pull/33/commits/7f78bcb28430eea15e659c21111de58757df0923](https://github.com/lunasoft/sw-sdk-java/pull/33/commits/7f78bcb28430eea15e659c21111de58757df0923)
